### ISSUE TITLE
Steward Removed from protocols

### ISSUE THREAD

**Issue by KelleyCoda** [MukurtuCMS/mukurtucms#33]
As a Mukurtu Admin, when I change my username, I am being removed from protocols that I steward. 

This is occurring under the following circumstances:
- User is a Mukurtu Admin
- User is a member and a steward of the protocol, but did not create the protocol

This is not occurring under the following circumstances:
- User is not a Mukurtu Admin and the username is changed for them.
- User is a steward of a protocol and creator of the protocol
- User is a contributor or no-role member of the protocol

Tested on multiple sites. Seems to be occurring in all of them.

**Comment by steve-taylor-wsu** [comment]
Hi Kelley,

This is part of a larger bug, where whenever a user's profile is updated (name change, email change, role change...) most or all of their protocol memberships can be lost. We have this fixed in develop currently, scheduled for inclusion in 2.0.5. For me this borders on hotfix territory, but we were really hoping to hold off to test the patch better. If this is something that you need right away I can send you a patch.

**Comment by KelleyCoda** [comment]
Whew, I was actually going to note that it happens whenever the profile is updated. I have a site where a user is a steward of 30+ protocols (not created themselves) and she updated her password yesterday :-/ Even so, I think that the patch should be tested, so we'll wait for 2.0.5

**Comment by steve-taylor-wsu** [comment]
This has been fixed in 2.0.5. Thanks.
