### ISSUE TITLE
Drupal already installed

### ISSUE THREAD

**Issue by dartion5** [MukurtuCMS/mukurtucms#88]
Hi Team,

I've been working on Mukurtu theme/module development from the past 2 weeks. I had a local VM (XAMPP - Mac OSX) installed and running. 
However, I changed my work environment(OS and Virtual Machine) and tried to install Mukurtu again. I'm getting the message 
"Drupal already installed". 
I tried to go through Drupal forums to search for a  work around for this problem but was not helpful. 

FYI,
I've got an Apache2, mysql and Ubuntu OS on cloud.

Can you help me install Mukurtu on my VM?

Kind Regards
Darshan

**Comment by steve-taylor-wsu** [comment]
Hi Darshan,

This is usually due to a non-empty pre-existing database or a problem with the settings.php file.

If you are installing a brand new instance of Mukurtu, I'd recommend you make sure the database you've selected is empty (no tables) or create a brand new database.

Also I've found that manually creating and configuring the settings.php file before starting the install is more reliable compared to using the web interface. If you don't have a settings.php file, copy and rename the file "/sites/default/default.settings.php" to "/sites/default/settings.php", open it in your text editor, go to the bottom and fill out the options (e.g., 'database', 'username', 'password'). Save the file and then start the install process.

Let me know if that doesn't work. Thanks.

Steve

**Comment by dartion5** [comment]
Thanks Steve,

That was quick and very helpful!

Creating new database and manually configuring settings.php solved my problem.
